# Generated by Django 4.2.1 on 2024-02-07 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionchoices', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionchoices.questionchoice', verbose_name='Ответы')),
                ('question_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_for_user', to='questions.question', verbose_name='Вопросы')),
                ('user_id', models.ManyToManyField(default=None, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
