# Generated by Django 4.2.1 on 2024-02-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField(verbose_name='Вариант ответа')),
                ('is_right_choice', models.BooleanField(choices=[(False, 'Неверный ответ'), (True, 'Верный ответ')])),
                ('question', models.ManyToManyField(blank=True, related_name='answers', to='questions.question', verbose_name='Вопросы')),
            ],
        ),
    ]
